default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  port: 3306
  username: root
  password: hanchen
development:
  <<: *default
  database: payments

test:
  <<: *default
  database: payments_test